export type NoteName =
  | 'C'
  | 'C#'
  | 'Db'
  | 'D'
  | 'D#'
  | 'Eb'
  | 'E'
  | 'F'
  | 'F#'
  | 'Gb'
  | 'G'
  | 'G#'
  | 'Ab'
  | 'A'
  | 'A#'
  | 'Bb'
  | 'B';

export type ChordName =
  | 'fifth'
  | 'suspended fourth'
  | 'suspended fourth seventh'
  | 'augmented'
  | 'major seventh flat sixth'
  | 'augmented seventh'
  | 'major'
  | 'major seventh'
  | 'dominant seventh'
  | 'sixth'
  | 'major seventh sharp eleventh'
  | 'lydian dominant seventh'
  | 'minor augmented'
  | 'minor'
  | 'minor/major seventh'
  | 'minor seventh'
  | 'minor sixth'
  | 'diminished'
  | 'half-diminished'
  | 'diminished seventh'
  | 'dominant sharp ninth'
  | 'suspended second'
  | 'eleventh'
  | 'major ninth'
  | 'dominant ninth'
  | 'sixth/ninth'
  | 'major thirteenth'
  | 'dominant thirteenth'
  | 'major sharp eleventh (lydian)'
  | 'minor/major ninth'
  | 'minor ninth'
  | 'minor thirteenth'
  | 'minor eleventh'
  | 'suspended fourth flat ninth'
  | 'altered'
  | 'dominant flat ninth';

export type ScaleName =
  | 'major pentatonic'
  | 'ionian pentatonic'
  | 'mixolydian pentatonic'
  | 'ritusen'
  | 'egyptian'
  | 'neopolitan major pentatonic'
  | 'vietnamese 1'
  | 'pelog'
  | 'kumoijoshi'
  | 'hirajoshi'
  | 'iwato'
  | 'in-sen'
  | 'lydian pentatonic'
  | 'malkos raga'
  | 'locrian pentatonic'
  | 'minor pentatonic'
  | 'minor six pentatonic'
  | 'flat three pentatonic'
  | 'flat six pentatonic'
  | 'scriabin'
  | 'whole tone pentatonic'
  | 'lydian #5P pentatonic'
  | 'lydian dominant pentatonic'
  | 'minor #7M pentatonic'
  | 'super locrian pentatonic'
  | 'minor hexatonic'
  | 'augmented'
  | 'major blues'
  | 'piongio'
  | 'prometheus neopolitan'
  | 'prometheus'
  | 'mystery #1'
  | 'six tone symmetric'
  | 'whole tone'
  | "messiaen's mode #5"
  | 'minor blues'
  | 'locrian major'
  | 'double harmonic lydian'
  | 'harmonic minor'
  | 'altered'
  | 'locrian #2'
  | 'mixolydian b6'
  | 'lydian dominant'
  | 'lydian'
  | 'lydian augmented'
  | 'dorian b2'
  | 'melodic minor'
  | 'locrian'
  | 'ultralocrian'
  | 'locrian 6'
  | 'augmented heptatonic'
  | 'romanian minor'
  | 'dorian #4'
  | 'lydian diminished'
  | 'phrygian'
  | 'leading whole tone'
  | 'lydian minor'
  | 'phrygian dominant'
  | 'balinese'
  | 'neopolitan major'
  | 'aeolian'
  | 'harmonic major'
  | 'double harmonic major'
  | 'dorian'
  | 'hungarian minor'
  | 'hungarian major'
  | 'oriental'
  | 'flamenco'
  | 'todi raga'
  | 'mixolydian'
  | 'persian'
  | 'major'
  | 'enigmatic'
  | 'major augmented'
  | 'lydian #9'
  | "messiaen's mode #4"
  | 'purvi raga'
  | 'spanish heptatonic'
  | 'bebop'
  | 'bebop minor'
  | 'bebop major'
  | 'bebop locrian'
  | 'minor bebop'
  | 'diminished'
  | 'ichikosucho'
  | 'minor six diminished'
  | 'half-whole diminished'
  | 'kafi raga'
  | "messiaen's mode #6"
  | 'composite blues'
  | "messiaen's mode #3"
  | "messiaen's mode #7"
  | 'chromatic';
